# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-18 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0002_auto_20171118_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='/static/images/profile.jpg', upload_to='/static/images/projects'),
        ),
    ]
