# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-21 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0007_auto_20180320_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
